
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    restart: unless-stopped
    depends_on:
      - database
    networks:
      - app_network
    volumes:
      - app_upload_files:/app/var/uploads
      - .:/app
    environment:
      DATABASE_URL: ${DATABASE_URL}
      PHP_UPLOAD_MAX_FILESIZE: 500M
      PHP_POST_MAX_SIZE: 500M
      PHP_MEMORY_LIMIT: 2G
    ports:
      - "8002:8002"

  database:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app_network

networks:
  app_network:

volumes:
  app_upload_files:
  mysql_data: