# curl -X POST -F "file=@/path/to/your/file.csv" http://localhost:8002/upload/csv
POST http://localhost:8002/api/employee
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="file.csv"

< /home/amir/Downloads/import.csv
--WebAppBoundary--

###

