###

# curl -X GET http://localhost:8002/api/employee/470143
GET http://localhost:8002/api/employee/470143

###

# curl -X DELETE http://localhost:8002/api/employee/198429
DELETE http://localhost:8002/api/employee/470143

###

